### ISSUE TITLE
recommendation triggered on wrong site

### ISSUE THREAD

**Issue by designakt** [mozilla/addon-recommendation-shield-study#79]
I got the RT News add-on recommended on http://meiert.com/en/ which is not a right match.
![siteenhance-rtcom_on_meiertcom](https://cloud.githubusercontent.com/assets/8145891/17739753/66ff6d08-6496-11e6-84f0-568966e1dabf.PNG)

**Comment by gregglind** [comment]
I am not conviced that www. is needed for _all of these_.  RT is the oddity here.  I claim the others are unlikely to be triggered by accident.  I claim F- but R+ .

**Comment by bentoncase** [comment]
I think that the issue occurred because previously my code would just check to see that the recommendation domain is a substring of the current domain. I'm now using sdk/url hostname method for stronger comparison, which includes the subdomain. I added www. for all of the recommendation sites that use it (soundcloud.com does not)
